package it.polimi.ingsw.PSP38.client;

import it.polimi.ingsw.PSP38.client.GUIComponents.BoardComponent;
import it.polimi.ingsw.PSP38.client.GUIComponents.ConnectionComponent;
import it.polimi.ingsw.PSP38.client.GUIComponents.SetNumOfPlayersComponent;
import it.polimi.ingsw.PSP38.client.GUIComponents.SetupWindow;
import it.polimi.ingsw.PSP38.common.Message;
import it.polimi.ingsw.PSP38.common.Protocol;
import it.polimi.ingsw.PSP38.common.utilities.Observer;

import javax.swing.*;
import java.io.IOException;
import java.lang.reflect.InvocationTargetException;
import java.net.InetAddress;
import java.net.Socket;
import java.util.Observable;
import java.util.Scanner;


/**
 * Executable class for the client side of Santorini
 * this class is responsible for showing to users all new messages from the server, the last board updated
 * and notify the class Client for all user inputs
 */
public class Client extends Observable implements Observer {
    private final static int SERVER_SOCKET_PORT = 3456;
    private static final Scanner scanner = new Scanner(System.in);
    private static String dataInput;
    private static ServerHandler nextInputObserver;
    private static GameMode gameMode;
    private static String customString;
    private static BoardComponent sc;
    private static Socket serverSocket;
    private static ConnectionComponent cc;
    private static SetNumOfPlayersComponent snpc;
    private static SetupWindow setupWindow;
    private static String ipAddress;

    public static void main(String[] args) throws InvocationTargetException, InterruptedException {
        if (args.length==0) {
            SwingUtilities.invokeAndWait(() -> {
                /*JFrame frame = createUI();
                cc.createConnectionWindow();
                snpc = new SetNumOfPlayersComponent();
                snpc.createNumOfPlayers();
                frame.add(snpc);*/
                setupWindow = new SetupWindow();
                setupWindow.createSetupWindow();
            });
        } else if (args[0].equalsIgnoreCase("cli")) {
            gameMode = new GameModeCLI();
            System.out.println("Insert ip address:");
            ipAddress= scanner.nextLine();
            connectionHandling(ipAddress, SERVER_SOCKET_PORT);
            while (true) {
                dataInput = gameMode.nextInput();
                notifyReadSomething();
            }
        } else {
            System.out.println("Parameter not recognized");
        }
    }

    /**
     * This method is used to show the game's board generated by the server on client's screen
     */
    private static void displayBoard() {
        gameMode.displayBoard();
    }

    /**
     * When Client class receives a new protocol from the server this methods call </@printMessage()> or </displayBoard> to show the new update
     */
    @Override
    public void update() {
        Protocol protocolRead = ServerHandler.getProtocol();
        if (protocolRead == Protocol.NOTIFY_MESSAGE) {
            //printMessage(ServerHandler.getMessage());
            gameMode.decodeMessage(ServerHandler.getMessage());
        }
        if (protocolRead == Protocol.DISPLAY_BOARD) {
            displayBoard();
        }
        if (protocolRead == Protocol.NOTIFY_CUSTOM_STRING) {
            customString = ServerHandler.getCustomMessageString();
            gameMode.updateCustomString();
        }
    }

    /**
     * @return the last data read
     */
    public static String getStringInput() {
        return dataInput;
    }

    /**
     * notify observers that is available a new data input from the client
     */
    private static void notifyReadSomething() {
        Protocol protocolRead = ServerHandler.getProtocol();
        if (protocolRead == Protocol.ASK_INT || protocolRead == Protocol.ASK_STRING) {
            nextInputObserver.update();
        } else {
            gameMode.decodeMessage(Message.WAIT);
        }

    }

    public static JFrame createUI() {
        JFrame frame = new JFrame();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        cc=new ConnectionComponent();
        frame.add(cc);
        frame.getContentPane().setPreferredSize(cc.getPreferredSize());
        frame.pack();
        frame.setVisible(true);
        cc.requestFocusInWindow();
        return frame;
    }

    public static String getCustomString() {
        return customString;
    }

    public static void connectionHandling(String address, int port){
        try {
            InetAddress addr = InetAddress.getByName(address);
            serverSocket = new Socket(addr, port);
            ServerHandler serverHandler = new ServerHandler(serverSocket);
            nextInputObserver = serverHandler;
            Thread thread = new Thread(serverHandler);
            thread.start();
        } catch (IOException e) {
            System.out.println("server unreachable");
            return;
        }
        System.out.println("Connected");
    }
}